/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javabank.view;

import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javabank.model.Cliente;
import javabank.ClienteTableModel;
import javabank.model.ContaCorrente;
import javabank.model.ContaInvestimento;
import javabank.ContaTableModel;
import javabank.controller.ClienteController;
import javabank.controller.ContaController;
import javabank.model.Conta;

/**
 *
 * @author maico
 */
public class ViewBanco extends javax.swing.JFrame {

    private ClienteTableModel modeloCliente = new ClienteTableModel();
    private ContaTableModel modeloConta = new ContaTableModel();

    private ClienteController controller;
    
    private ContaController controller_conta;
    

    long numconta;

    public ViewBanco() {
        initComponents();
        jLayeredPane1.setVisible(false);
        jLayeredPaneFieldsInvestmento.setVisible(false);
        jButtonContaCorrente.setVisible(false);
        jButtonContaInvestimento.setVisible(false);
        jNumContaC.setText("");
        jNumContaI.setText("");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldRg = new javax.swing.JTextField();
        botaoCriar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jLabelSnome = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFieldSNome = new javax.swing.JTextPane();
        jLabelEndereco = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextEndereco = new javax.swing.JTextPane();
        jLabelSalario = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextSalario = new javax.swing.JTextPane();
        LimparCampos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        contaCombo = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jDepositoC = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jLimiteC = new javax.swing.JTextPane();
        jButtonContaCorrente = new javax.swing.JButton();
        jNumContaC = new javax.swing.JLabel();
        jLayeredPaneFieldsInvestmento = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jMontanteMinI = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jDepositoMin = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jDepositoInicialI = new javax.swing.JTextPane();
        jButtonContaInvestimento = new javax.swing.JButton();
        jNumContaI = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonSaldo = new javax.swing.JButton();
        jButtonRemunerar = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPaneDeposito = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonSacar = new javax.swing.JButton();
        jButtonDepositar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabelCpf.setText("CPF:");

        jLabelRG.setText("RG:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });

        botaoCriar.setText("Criar");
        botaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizar.setText("Alterar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jLabelSnome.setText("Sobrenome:");

        jScrollPane3.setViewportView(jTextFieldSNome);

        jLabelEndereco.setText("Endereço:");

        jScrollPane4.setViewportView(jTextEndereco);

        jLabelSalario.setText("Salario:");

        jScrollPane5.setViewportView(jTextSalario);

        LimparCampos.setText("Limpar Campos");
        LimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelEndereco)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelSnome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(botaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LimparCampos)
                                .addGap(0, 281, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCPF))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jTextFieldRg))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane5))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSnome)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCpf)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRG)
                    .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEndereco)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCriar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizar)
                    .addComponent(LimparCampos))
                .addContainerGap())
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(modeloCliente);
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Lista de Clientes");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro Cliente", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jScrollPane9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane9MouseClicked(evt);
            }
        });

        jTable2.setModel(modeloCliente);
        jScrollPane9.setViewportView(jTable2);

        jLabel8.setText("Lista de Clientes");

        contaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-","Conta Corrente", "Conta Investimento"}));
        contaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contaComboActionPerformed(evt);
            }
        });

        jLabel10.setText("Número Conta:");

        jLabel2.setText("Deposito Inicial:");

        jLabel3.setText("Limite:");

        jScrollPane7.setViewportView(jDepositoC);

        jScrollPane8.setViewportView(jLimiteC);

        jButtonContaCorrente.setText("Criar Conta");
        jButtonContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContaCorrenteActionPerformed(evt);
            }
        });

        jNumContaC.setText("XXXXXX");

        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButtonContaCorrente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jNumContaC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jNumContaC)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addComponent(jScrollPane8))))
                        .addGap(26, 26, 26))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jButtonContaCorrente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jNumContaC))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonContaCorrente)
                .addContainerGap())
        );

        jLabel11.setText("Número Conta:");

        jLabel4.setText("Montante Minimo:");

        jLabel5.setText("Deposito Minimo:");

        jLabel6.setText("Deposito Inicial:");

        jScrollPane11.setViewportView(jMontanteMinI);

        jScrollPane12.setViewportView(jDepositoMin);

        jScrollPane13.setViewportView(jDepositoInicialI);

        jButtonContaInvestimento.setText("Criar Conta");
        jButtonContaInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContaInvestimentoActionPerformed(evt);
            }
        });

        jNumContaI.setText("XXXXXX");

        jLayeredPaneFieldsInvestmento.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jScrollPane11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jButtonContaInvestimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneFieldsInvestmento.setLayer(jNumContaI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneFieldsInvestmentoLayout = new javax.swing.GroupLayout(jLayeredPaneFieldsInvestmento);
        jLayeredPaneFieldsInvestmento.setLayout(jLayeredPaneFieldsInvestmentoLayout);
        jLayeredPaneFieldsInvestmentoLayout.setHorizontalGroup(
            jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneFieldsInvestmentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jLayeredPaneFieldsInvestmentoLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane13))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneFieldsInvestmentoLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane12))
                        .addGroup(jLayeredPaneFieldsInvestmentoLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                        .addGroup(jLayeredPaneFieldsInvestmentoLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jNumContaI)))
                    .addComponent(jButtonContaInvestimento))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneFieldsInvestmentoLayout.setVerticalGroup(
            jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneFieldsInvestmentoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jNumContaI))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneFieldsInvestmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonContaInvestimento)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPaneFieldsInvestmento)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(contaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPaneFieldsInvestmento))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Criar Conta", jPanel2);

        jLabel9.setText("Saque:");

        jLabel12.setText("Depósito:");

        jLabel13.setText("Ações:");

        jButtonSaldo.setText("Saldo");
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });

        jButtonRemunerar.setText("Remunerar");
        jButtonRemunerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemunerarActionPerformed(evt);
            }
        });

        jScrollPane10.setViewportView(jTextPaneDeposito);

        jScrollPane14.setViewportView(jTextPane2);

        jLabel14.setText("R$");

        jLabel15.setText("R$");

        jButtonSacar.setText("Sacar");
        jButtonSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacarActionPerformed(evt);
            }
        });

        jButtonDepositar.setText("Depositar");
        jButtonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemunerar))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jScrollPane14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSacar))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDepositar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jButtonSacar)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDepositar)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButtonSaldo)
                    .addComponent(jButtonRemunerar))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTable4.setModel(modeloConta);
        jScrollPane15.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manipular Conta", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initView() {
        java.awt.EventQueue.invokeLater(() -> this.setVisible(true));
        this.controller.listarCliente();
        
    }

    public void setController(ClienteController controller) {
        this.controller = controller;
    }
    
    public void setControllerConta(ContaController controller) {
        this.controller_conta = controller;
        this.controller_conta.listarContas();
    }
    
    public void mostrarListaClientes(List<Cliente> list) {
       
        this.modeloCliente.setListaContatos(list);
        //this.modeloCliente.adicionaContato(x);
        //System.out.println("aabbba");
    }
    
    public void mostrarContas(List<Conta> list){
        this.modeloConta.setContas(list);
    }
    
    public void adicionarCliente (Cliente c){
       this.modeloCliente.adicionaContato(c);
    }

    public void mostarMensagemInfo(String mensagem ){
        JOptionPane.showMessageDialog(null, mensagem,"INFO" ,JOptionPane.INFORMATION_MESSAGE);
    }

    private void botaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarActionPerformed
        //Aqui eu vou escrever o código
        try {
            String nome = jTextFieldNome.getText();
            String cpf = jTextFieldCPF.getText();
            String snome = jTextFieldSNome.getText();
            String rg = jTextFieldRg.getText();
            String endereco = jTextEndereco.getText();
            String salario = jTextSalario.getText();
            double dsalario = Double.parseDouble(salario);

            Cliente cliente = new Cliente(nome, snome, cpf, rg, dsalario, endereco);
            this.controller.inserirCliente(cliente);
            //List<Cliente> lista = new ArrayList();
            //lista.add(cliente);
            //this.mostrarListaClientes(lista);
            //BancoDados.listaClientes.add(cliente);
            //   modeloCliente.adicionaContato(cliente);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data inválida.\n", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_botaoCriarActionPerformed
    
    
    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            int opcao_escolhida = JOptionPane
                    .showConfirmDialog(null,
                            "Deseja atualizar as informações do cliente?",
                            "Excluir",
                            JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                String nome = jTextFieldNome.getText();
                String cpf = jTextFieldCPF.getText();
                String snome = jTextFieldSNome.getText();
                String rg = jTextFieldRg.getText();
                String endereco = jTextEndereco.getText();
                String salario = jTextSalario.getText();
                double dsalario = Double.parseDouble(salario);
                modeloCliente.setValueAt(nome, jTable1.getSelectedRow(), 0);
                modeloCliente.setValueAt(cpf, jTable1.getSelectedRow(), 2);
                modeloCliente.setValueAt(snome, jTable1.getSelectedRow(), 1);
                modeloCliente.setValueAt(rg, jTable1.getSelectedRow(), 3);
                modeloCliente.setValueAt(endereco, jTable1.getSelectedRow(), 4);
                modeloCliente.setValueAt(dsalario, jTable1.getSelectedRow(), 5);
                //System.out.println(modeloCliente.getContato(jTable1.getSelectedRow()).getId());
                long id = modeloCliente.getContato(jTable1.getSelectedRow()).getId();
                Cliente cliente = new Cliente(id,nome, snome, cpf, rg, dsalario ,endereco );
                this.controller.updateCliente(cliente);

            }
        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if (jTable1.getSelectedRow() != -1) {
            int opcao_escolhida = JOptionPane
                    .showConfirmDialog(null,
                            "Deseja excluir TODAS as informações do cliente?",
                            "Excluir",
                            JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                //System.out.println(modeloCliente.getContato(jTable1.getSelectedRow()));
                modeloCliente.removeCliente(jTable1.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jScrollPane9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane9MouseClicked

    private void contaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contaComboActionPerformed
        switch (contaCombo.getSelectedIndex()) {
            case 1:
                System.out.print("Conta Corrente");
                jLayeredPaneFieldsInvestmento.setVisible(false);
                jLayeredPane1.setVisible(true);
                jButtonContaCorrente.setVisible(true);
                break;
            case 2:
                System.out.print("Conta Investimento");
                jLayeredPane1.setVisible(false);
                jLayeredPaneFieldsInvestmento.setVisible(true);
                jButtonContaInvestimento.setVisible(true);
                break;
            case 0:
                System.out.print("Conta nada");
                jLayeredPane1.setVisible(false);
                jLayeredPaneFieldsInvestmento.setVisible(false);
                jButtonContaCorrente.setVisible(false);
                jButtonContaInvestimento.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_contaComboActionPerformed
    
    
    public void adicionarConta(Conta conta){
        //System.out.println("adicionarConta");
        modeloConta.adicionaListaConta(conta);
    }
    
    
    private void jButtonContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContaCorrenteActionPerformed

        try {
 
            System.out.println(this.numconta);
            String saldo = jDepositoC.getText();
            double dsaldo = Double.parseDouble(saldo);
            //String numero = jNumContaC.getText();
            //int inumero = parseInt(numero);
            String limite = jLimiteC.getText();
            double dlimite = Double.parseDouble(limite);
            String dono;
            if (jTable2.getSelectedRow() != -1) {
                
                dono = (String) modeloCliente.getValueAt(jTable2.getSelectedRow(), 2);
                System.out.println(dono);
                
                ContaCorrente conta = new ContaCorrente();
                conta.setDepositoInicial(dsaldo);
                conta.setSaldo(dsaldo);
                conta.setLimite(dlimite);
                
                conta.setCliente(this.controller.buscaClienteCpf(dono));
                
                this.controller_conta.inserirContaCorrente(conta);

                //modeloConta.adicionaListaConta(conta);
                JOptionPane.showMessageDialog(null, "Conta Criada Com Sucesso.\n", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                numconta = this.controller_conta.buscaNumConta(this.controller.buscaClienteCpf(dono).getId());
                System.out.println("Num conta recem criada: " + numconta);
    
                jNumContaC.setText(Long.toString(numconta));
                jNumContaI.setText(Long.toString(numconta));
                
                
                 this.controller.listarClienteSemConta();
            }
            
            //System.out.println(dono);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Dados Insuficientes.\n", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonContaCorrenteActionPerformed

    private void jButtonContaInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContaInvestimentoActionPerformed
        
        try {
            String saldo = jDepositoInicialI.getText();
            double dsaldo = Double.parseDouble(saldo);
            //String numero = jNumContaI.getText();
            //int inumero = parseInt(numero);
            
            String montanteMin = jMontanteMinI.getText();
            double dmontanteMinimo = Double.parseDouble(montanteMin);
            String depositoMin = jDepositoMin.getText();
            double ddepositoMinimo = Double.parseDouble(depositoMin);
            String dono;
            
            if (jTable2.getSelectedRow() != -1) {
                dono = (String) modeloCliente.getValueAt(jTable2.getSelectedRow(), 2);
                ContaInvestimento conta = new ContaInvestimento();
                conta.setDepositoMinimo(ddepositoMinimo);
                conta.setMontanteMinimo(dmontanteMinimo);
                conta.setSaldo(dsaldo);
                
                conta.setCliente(this.controller.buscaClienteCpf(dono));
                this.controller_conta.inserirContaInvestimento(conta);
                
                //modeloConta.adicionaListaConta(conta);
                JOptionPane.showMessageDialog(null, "Conta Criada Com Sucesso.\n", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                numconta = this.controller_conta.buscaNumConta(this.controller.buscaClienteCpf(dono).getId());

                jNumContaI.setText(Long.toString(numconta));
                jNumContaC.setText(Long.toString(numconta));
                
                this.controller.listarClienteSemConta();
            }
   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Dados Insuficientes.\n", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_jButtonContaInvestimentoActionPerformed

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
        if (jTable4.getSelectedRow() != -1) {
            String saldo = Double.toString((double) modeloConta.getValueAt(jTable4.getSelectedRow(), 2));
            JOptionPane.showMessageDialog(null, "R$ " + saldo, "SALDO", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonRemunerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemunerarActionPerformed
        if (jTable4.getSelectedRow() != -1) {
            Conta conta = modeloConta.getContaRemunera(jTable4.getSelectedRow());
            this.controller_conta.Remunerar(conta);
            JOptionPane.showMessageDialog(null, "Remuneração Realizada!", "Remuneração", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRemunerarActionPerformed

    private void jButtonSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacarActionPerformed
        try {
            if (jTable4.getSelectedRow() != -1) {
                
                String sValor = jTextPane2.getText();
                double valor = Double.parseDouble(sValor);
                
                Conta conta = modeloConta.getValueAt(jTable4.getSelectedRow(), 1, valor);  

                if (this.controller_conta.Sacar(conta, valor)) {
                    JOptionPane.showMessageDialog(null, "Saque Realizado!", "Saque", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Sacar!", "Saque", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Valor Inválido!.\n", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonSacarActionPerformed

    private void jButtonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositarActionPerformed
        try {
            if (jTable4.getSelectedRow() != -1) {
                
                String sValor = jTextPaneDeposito.getText();
                double valor = Double.parseDouble(sValor);
                
                Conta conta = modeloConta.getValueAt(jTable4.getSelectedRow(), 1, valor);  

                if (this.controller_conta.Depositar(conta, valor)) {
                    JOptionPane.showMessageDialog(null, "Deposito Realizado!", "Saque", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao depositar!", "Saque", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Valor Inválido!.\n", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButtonDepositarActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void LimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCamposActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setText("");
        jTextFieldSNome.setText("");
        jTextFieldRg.setText("");
        jTextFieldCPF.setText("");
        jTextEndereco.setText("");
        jTextSalario.setText("");
    }//GEN-LAST:event_LimparCamposActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        this.controller.listarClienteSemConta();
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        if(this.controller != null){
            this.controller.listarCliente();
        }
        
    }//GEN-LAST:event_jPanel1ComponentShown
    
    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) { 
        
        if (jTable1.getSelectedRow() != -1) {
            int linha = jTable1.getSelectedRow();
            String nome = jTable1.getValueAt(linha, 0).toString();        
            String sobrenome = jTable1.getValueAt(linha, 1).toString();
            String rg = jTable1.getValueAt(linha, 2).toString();
            String cpf = jTable1.getValueAt(linha, 3).toString();
            String endereco = jTable1.getValueAt(linha, 4).toString();
            String salario = jTable1.getValueAt(linha, 5).toString();
            
            jTextFieldNome.setText(nome);
            jTextFieldSNome.setText(sobrenome);
            jTextFieldRg.setText(rg);
            jTextFieldCPF.setText(cpf);
            jTextEndereco.setText(endereco);
            jTextSalario.setText(salario);
        }
    }   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBanco().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimparCampos;
    private javax.swing.JButton botaoCriar;
    private javax.swing.JComboBox<String> contaCombo;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonContaCorrente;
    private javax.swing.JButton jButtonContaInvestimento;
    private javax.swing.JButton jButtonDepositar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonRemunerar;
    private javax.swing.JButton jButtonSacar;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JTextPane jDepositoC;
    private javax.swing.JTextPane jDepositoInicialI;
    private javax.swing.JTextPane jDepositoMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSnome;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPaneFieldsInvestmento;
    private javax.swing.JTextPane jLimiteC;
    private javax.swing.JTextPane jMontanteMinI;
    private javax.swing.JLabel jNumContaC;
    private javax.swing.JLabel jNumContaI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextEndereco;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRg;
    private javax.swing.JTextPane jTextFieldSNome;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPaneDeposito;
    private javax.swing.JTextPane jTextSalario;
    // End of variables declaration//GEN-END:variables
}
